hw_env:
  env_type: virt_default
  network_cidr: 192.168.0.0/24
  floating_ip_end: "{{ installer.network.virt_floating_ip_end|default('172.16.23.240') }}"
  floating_ip_start: "{{ installer.network.virt_floating_ip_start|default('172.16.23.140') }}"
  floating_ip_cidr: "{{ installer.network.virt_floating_ip_cidr|default('172.16.23.128/25') }}"
  network_gateway: "{{ installer.network.virt_network_gateway|default('172.16.23.251') }}"
  network_type: "{{ installer.network.network_type|default('vlan') }}"
  physical_network: datacentre
  ExternalNetworkVlanID: "{{ installer.network.ExternalNetworkVlanID|default('10') }}"
